apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx
  labels:
    first: app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - name: my-container
          image: nginx

          ports:
            - containerPort: 80